### PR TITLE
Add gas table to FIP0057

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by jennijuju** [comment]
@Kubuxu Thank you! do we have the value for PreCommitBatch and provecommitaggregation?

**Comment by Kubuxu** [comment]
Not in the range of blocks I collected.

**Review by anorth — APPROVED** [review]
Editorial rubber stamp.

**Comment by jennijuju** [comment]
@Kubuxu @Stebalien id still like some value for those three messages as they are critical storage consensus/operation  messages.

**Review by jennijuju — APPROVED** [review]

**Comment by Kubuxu** [comment]
> id still like some value for those three messages as they are critical storage consensus/operation messages.

I'm aware, but the data collection I'm relaying on uses a live chain where these messages are not actively used.

@raulk might be able to collect some data on them with the standalone, on-demand migration software he is developing. Maybe we can apply it to a test vector of PCA and WindowPoSt dispute.

**Pull request merged**
