### PR TITLE
Update FIP-0006 to Deferred

### PR DESCRIPTION
**Pull request by arajasek**
As discussed in https://github.com/filecoin-project/tpm/issues/15

### CODE REVIEW

**Comment by momack2** [comment]
This would be our first "deferred". Is the aim of those that we ARE going to do it but just in a future upgrade, or just "not now"? IIRC, there were some research questions to land in the FIP that needed additional work - so Draft may be a better designation to indicate there's open work before approval...?

**Comment by jennijuju** [comment]
Could we please update the status in the [FIP table](https://github.com/filecoin-project/FIPs#fips) with status changing prs too?

**Comment by arajasek** [comment]
@momack2 Based on what we've said, "Deferred" means "a FIP that is not being considered for immediate adoption. May be reconsidered in the future for a subsequent chain upgrade." 

That sounds like what we agreed to, except that we likely will not be reconsidering in a future upgrade (and instead be opening a new, better FIP that achieves a similar purpose). Perhaps it's worth adding a more explicit "Rejected" state?

**Comment by momack2** [comment]
Sg, let’s move to “deferred” for now and we can separately consider the
recent changes to the EIP process we may want to adopt re “withdrawn”
proposals:
https://eips.ethereum.org/EIPS/eip-1#eip-process

**Review by jennijuju — APPROVED** [review]

**Review by momack2 — APPROVED** [review]

**Pull request merged**
