### PR TITLE
remove editors that have lower activities

### PR DESCRIPTION
**Pull request by jennijuju**
more discussion in https://github.com/filecoin-project/FIPs/discussions/960

@arajasek has 👍 this change.

@momack2 / @raulk have not engaged in the discussion yet, looking forward to their feedback on this PR if they have any objections. Otherwise, after get 2 approval from the remaining fip editors, I will merge this PR. Always happy to add folks back when they could allocate more of their time to help with the FIP editing work!

### CODE REVIEW

**Comment by jennijuju** [comment]
I will make the changes to @filecoin-project/fips-editors once this pr is approved

**Review by TippyFlitsUK — APPROVED** [review]

**Review by jsoares — APPROVED** [review]
As I explained in the discussion, I'm generally in favour of retaining anyone who expresses the wish to stay and resume work. I'm also fine with taking silence to mean assent.

**Review by raulk — APPROVED** [review]

**Comment by jennijuju** [comment]
> I'm generally in favour of retaining anyone who expresses the wish to stay and resume work. 

I agree!

**Comment by momack2** [comment]
I would like to stay as a FIP Editor so that I can help unblock PRs with addl reviews when they get stuck (as happened a few weeks back on F3). 🙏 Happy to also add more folks who step up though!

**Comment by raulk** [comment]
@jennijuju it looks like this has garnered the desired level of approvals. Should we go ahead and merge to formally relieve outgoing FIP editors of their duties? (We seem to be in some form of a limbo.)

**Review by anorth — APPROVED** [review]

**Comment by luckyparadise** [comment]
@jennijuju could we close this PR and reverse @momack2 removal as she has indicated an interest in continuing to play the role of a FIP Editor? I believe we need to remove Ayush and Raul.

**Comment by jsoares** [comment]
> @jennijuju could we close this PR and reverse @momack2 removal as she has indicated an interest in continuing to play the role of a FIP Editor? I believe we need to remove Ayush and Raul.

Does that require a new PR? Not opposed to making said changes here.

**Comment by jsoares** [comment]
It appears to me that @arajasek and @raulk have consented to the change and are _de facto_ no longer active, with no FIP reviews in the last 6 months. @momack2, on the other hand, remains active and wishes to remain active.

For the sake of unblocking this, would @filecoin-project/fips-editors be okay with @luckyparadise's proposal above of descoping Molly from this PR and merging the remaining changes? I can make the commit, but only if we have upfront buy-in.

**Comment by jennijuju** [comment]
> It appears to me that @arajasek and @raulk have consented to the change and are _de facto_ no longer active, with no FIP reviews in the last 6 months. @momack2, on the other hand, remains active and wishes to remain active.
> 
> For the sake of unblocking this with mere housekeeping rather than controversy, would @filecoin-project/fips-editors be okay with @luckyparadise's proposal above of descoping Molly from this PR and merging the remaining changes? I can commit the changes, but only if we have upfront buy-in.

made the change. given @jsoares proposed the update, and @anorth and myself 👍 , which mean 3 editors agrees with the proposal and that meets the required # for approval. So i am merging this PR without requesting FIP editors who has approved the PR to re-review.

**Pull request merged**
