### PR TITLE
Merge multiple transactions into one

### PR DESCRIPTION
**Pull request by IversonHan**
add fip0027 about merge multiple transactions into a single transaction optimizes the user experience and reduces user overhead as paying for each transaction is expensive and cumbersome.

### CODE REVIEW

**Comment by kaitlin-beegle** [comment]
> 

Hey @IversonHan! Thanks for the work on this FIP so far! 

As an FYI, I've renamed the PR to reflect the name of the FIP.  Would you mind removing "FIP0027" from the header? FIP numbers are assigned by the FIP editor once the FIP enters 'Last Call' status.  Doing so earlier tends to create confusion :) 

I'm also curious about the work status on this FIP.  Are you still updating specs, etc., or are you simply awaiting review?

**Comment by IversonHan** [comment]
> > 
> 
> Hey @IversonHan! Thanks for the work on this FIP so far!
> 
> As an FYI, I've renamed the PR to reflect the name of the FIP. Would you mind removing "FIP0027" from the header? FIP numbers are assigned by the FIP editor once the FIP enters 'Last Call' status. Doing so earlier tends to create confusion :)
> 
> I'm also curious about the work status on this FIP. Are you still updating specs, etc., or are you simply awaiting review?

Hey @kaitlin-beegle !Yeah, I'm still updating. However, the transaction aggregation part of the function is actually finished, I am not sure that my code implementation of the transaction aggregation is in line with your expectations, from the test results, it is in line with the purpose of reducing costs and transaction aggregation. I have been waiting for your reply. I want to know whether my work is meaningful or not. Thank you. As for the title change, I don't mind.

**Comment by kaitlin-beegle** [comment]
> > > 
> > 
> > 
> > Hey @IversonHan! Thanks for the work on this FIP so far!
> > As an FYI, I've renamed the PR to reflect the name of the FIP. Would you mind removing "FIP0027" from the header? FIP numbers are assigned by the FIP editor once the FIP enters 'Last Call' status. Doing so earlier tends to create confusion :)
> > I'm also curious about the work status on this FIP. Are you still updating specs, etc., or are you simply awaiting review?
> 
> Hey @kaitlin-beegle !Yeah, I'm still updating. However, the transaction aggregation part of the function is actually finished, I am not sure that my code implementation of the transaction aggregation is in line with your expectations, from the test results, it is in line with the purpose of reducing costs and transaction aggregation. I have been waiting for your reply. I want to know whether my work is meaningful or not. Thank you. As for the title change, I don't mind.

Amazing, thank you for the quick response! :) 

Right now, all FIP reviewers are focused on preparing FIPs for the v15 network upgrade.  However, I will add your FIP to the review list so you can get feedback on the technical specs, etc.

**Comment by IversonHan** [comment]
> > > > 
> > > 
> > > 
> > > Hey @IversonHan! Thanks for the work on this FIP so far!
> > > As an FYI, I've renamed the PR to reflect the name of the FIP. Would you mind removing "FIP0027" from the header? FIP numbers are assigned by the FIP editor once the FIP enters 'Last Call' status. Doing so earlier tends to create confusion :)
> > > I'm also curious about the work status on this FIP. Are you still updating specs, etc., or are you simply awaiting review?
> > 
> > 
> > Hey @kaitlin-beegle !Yeah, I'm still updating. However, the transaction aggregation part of the function is actually finished, I am not sure that my code implementation of the transaction aggregation is in line with your expectations, from the test results, it is in line with the purpose of reducing costs and transaction aggregation. I have been waiting for your reply. I want to know whether my work is meaningful or not. Thank you. As for the title change, I don't mind.
> 
> Amazing, thank you for the quick response! :)
> 
> Right now, all FIP reviewers are focused on preparing FIPs for the v15 network upgrade. However, I will add your FIP to the review list so you can get feedback on the technical specs, etc.

Oh, and I'm glad I saw my fip in the draft in the minutes from previous developer conferences. However, after I re-checked fips today, I found that fip#0028 was included in the v15 upgrade proposal, and fip#0027 was ignored. I wonder if this proposal will not be approved? Is it because the proposal is not allowed or is there something wrong with the code implementation?

**Comment by anorth** [comment]
@IversonHan a change like this would be quite foundational I do not think this draft FIP expresses a sufficiently concrete or detailed change. Immediate questions that come to mind include how the `Message` data structure is changed, how `BlockHeader` is changed (if necessary), execution semantics such as atomicity of individual messages or the group, handling of failure of a single message in a group, quantification of the gas savings we might actually gain, what alternative schemes might achieve the goals here and with what tradeoffs, etc.

I suggest opening a [discussion topic](https://github.com/filecoin-project/FIPs/discussions) first in order to flesh out some of these details, and come back with a FIP after a rough consensus and many fewer open questions.

I will close this PR in a few days.

**Comment by jennijuju** [comment]
In addition - Fip number is irrelevant to the priority of the FIPs or how soon it gets accepted / finalized in the network.

**Comment by kaitlin-beegle** [comment]
Closing FIP per @anorth's suggestions.  @IversonHan, this could be a great FIP, but more collaboration is needed to iron out the technical approach before a FIP draft is appropriate. 

If you have questions, or would like help opening up and publicizing that discussion post, please let me know!

**Comment by IversonHan** [comment]
> @IversonHan a change like this would be quite foundational I do not think this draft FIP expresses a sufficiently concrete or detailed change. Immediate questions that come to mind include how the `Message` data structure is changed, how `BlockHeader` is changed (if necessary), execution semantics such as atomicity of individual messages or the group, handling of failure of a single message in a group, quantification of the gas savings we might actually gain, what alternative schemes might achieve the goals here and with what tradeoffs, etc.
> 
> I suggest opening a [discussion topic](https://github.com/filecoin-project/FIPs/discussions) first in order to flesh out some of these details, and come back with a FIP after a rough consensus and many fewer open questions.
> 
> I will close this PR in a few days.

Ok, SO I'm opening up a new discussion, and I'm putting my own thinking and implementation here. This is the link: https://github.com/filecoin-project/FIPs/pull/219#issuecomment-1027430507

**Comment by IversonHan** [comment]
> > @IversonHan a change like this would be quite foundational I do not think this draft FIP expresses a sufficiently concrete or detailed change. Immediate questions that come to mind include how the `Message` data structure is changed, how `BlockHeader` is changed (if necessary), execution semantics such as atomicity of individual messages or the group, handling of failure of a single message in a group, quantification of the gas savings we might actually gain, what alternative schemes might achieve the goals here and with what tradeoffs, etc.
> > I suggest opening a [discussion topic](https://github.com/filecoin-project/FIPs/discussions) first in order to flesh out some of these details, and come back with a FIP after a rough consensus and many fewer open questions.
> > I will close this PR in a few days.
> 
> Ok, SO I'm opening up a new discussion, and I'm putting my own thinking and implementation here. This is the link: [#219 (comment)](https://github.com/filecoin-project/FIPs/pull/219#issuecomment-1027430507)

@kaitlin-beegle @anorth @jennijuju

**Comment by IversonHan** [comment]
> @IversonHan a change like this would be quite foundational I do not think this draft FIP expresses a sufficiently concrete or detailed change. Immediate questions that come to mind include how the `Message` data structure is changed, how `BlockHeader` is changed (if necessary), execution semantics such as atomicity of individual messages or the group, handling of failure of a single message in a group, quantification of the gas savings we might actually gain, what alternative schemes might achieve the goals here and with what tradeoffs, etc.
> 
> I suggest opening a [discussion topic](https://github.com/filecoin-project/FIPs/discussions) first in order to flesh out some of these details, and come back with a FIP after a rough consensus and many fewer open questions.
> 
> I will close this PR in a few days.

@kaitlin-beegle @jennijuju @anorth  Ok, SO I'm opening up a new discussion, and I'm putting my own thinking and implementation here. This is the link:https://github.com/filecoin-project/FIPs/discussions/291

**Pull request closed without merging**
