### PR TITLE
Jekyll website version of FIPs repo

### PR DESCRIPTION
**Pull request by bmann**
PR to go along with #124

 Uses a handful of elements from the Ethereum EIPs repo, which I also worked on.

Doesn't currently have "posts" turned on, but could for basic "what's new with this website".

See `WEBSITE.md` for the minimal details needed to build locally.

There are also edits to most of the FIPs to clean up inconsistencies, as well as some other written pages.

I know this is a very large PR, you can browse the current site at https://fips.fission.app

### CODE REVIEW

**Comment by kaitlin-beegle** [comment]
Noting that Boris and I have discussed this site on Slack as well; I think it's a great idea. 

It's more accessible than Github and provides a place for us to visually organize ideas and FIPs over time.

**Review by momack2 — APPROVED** [review]
(This isn’t a code review)

**Comment by bmann** [comment]
I have merged this with current master to keep things up to date, site continues to be auto-deployed to Fission here --> https://fips.fission.app/

With an auto table so @jennijuju doesn't have to suffer the horror of Markdown tables :)

**Comment by bmann** [comment]
I have merged master as of just now @momack2 @kaitlin-beegle to this PR, so if you want this in I would ask that it get merged soon so I'm not chasing master :)

Also: generally, the formating of FIPs is a little loose right now. I fixed it for FIP17 so it builds, need to follow the `name or handle (@github-handle or email)` format more closely, among other inconsistencies, but this will be more clear when the site is continuously built.

Can also get auto-building for PRs done for this, but that and getting the domain setup can also be done post-merge.

LMK if anything else needed here.

**Pull request merged**
