### PR TITLE
FIP-0076: Renumber the new methods to avoid collision with FIP-0070

### PR DESCRIPTION
**Pull request by anorth**
I don't believe this constitutes a substantive change to the FIP that should interrupt Last Call. The code in integration/direct-onboarding already reflects this after it was rebased against the FIP-0070 implementation.

CC @magik6k

### CODE REVIEW

**Review by jsoares — APPROVED** [review]

**Review by jennijuju — APPROVED** [review]

**Comment by jennijuju** [comment]
wait shouldnt the name be `XXX**3**`?

**Comment by kaitlin-beegle** [comment]
> wait shouldnt the name be `XXX**3**`?

I think in the spec they're specified only as numbers, without additional zeros formatting.  See: https://spec.filecoin.io/#example-storage-miner-actor

Agree?

**Comment by jennijuju** [comment]
> > wait shouldnt the name be `XXX**3**`?
> 
> I think in the spec they're specified only as numbers, without additional zeros formatting. See: https://spec.filecoin.io/#example-storage-miner-actor
> 
> Agree?

Sorry I meant the revised method names are ProveCommitSectors_**3**_ & so.

**Comment by anorth** [comment]
Chill out, this PR was concurrent with #886. Now that that has merged, I have de-conflicted.

**Comment by jennijuju** [comment]
Ah-ha, I knew I saw a PR with the right method number!! i thought I lost my mind for a sec haha

**Review by jennijuju — APPROVED** [review]

**Comment by jennijuju** [comment]
green tick re-added!

**Pull request merged**
