### PR TITLE
Introducing a Sector Duration Multiple for Longer Term Sector Commitment

### PR DESCRIPTION
**Pull request by vkalghatgi**

### CODE REVIEW

**Comment by Fatman13** [comment]
Is it normal that this FIP went from a FIP discussion to a PR in just 6 days? @kaitlin-beegle 

According to https://github.com/filecoin-project/FIPs/discussions/314,

> The lifecycle of a FIP is very long. Ideas that are added to the FIP Discussion Forum are often incrementally worked on over weeks or months.

Also according to https://github.com/filecoin-project/FIPs/discussions/314,

> FIP Authors are encouraged to share and solicit feedback on their discussion posts.

Authors literally shared no feedbacks to community's concerns and went straight to PR.

**Comment by jennijuju** [comment]
As an FIP editor speaking - Have a DRAFT fip PR open should be totally fine. authors should continue solicit the idea in the discussion, and update the DRAFT FIP accordingly before the DRAFT can be considered to move forward to LAST CALL.

**Comment by kaitlin-beegle** [comment]
> Is it normal that this FIP went from a FIP discussion to a PR in just 6 days? @kaitlin-beegle
> 
> According to #314,
> 
> > The lifecycle of a FIP is very long. Ideas that are added to the FIP Discussion Forum are often incrementally worked on over weeks or months.
> 
> Also according to #314,
> 
> > FIP Authors are encouraged to share and solicit feedback on their discussion posts.
> 
> > It is expected that the FIP Author is a public steward of their FIP, continuously seeking community feedback on their proposal, addressing questions and concerns, and moderating any public discussion which may arise in the discussion forum.
> 
> Authors engaged in no conversations with the community in the FIP discussion and went straight to PR.

You raise a fair point- it is preferable for there to be longer lead time between opening a discussion and pushing a FIP draft.  I went ahead and let the team know, so in the future we are aware in advance of any items that they're working on! 

However, @jennijuju is also correct: just because a PR is open or a FIP draft is merged, does not mean it is going to be accepted.  In fact, the team needs to respond to your comments, questions, concerns, etc., in the discussion before we can consider this ready for 'Last Call'.  

So, keep asking your questions! It's a good practice.

**Comment by steven004** [comment]
I think a basic problem here is that one might be confused to put comments here or in the discussion, and the author is willing to respond in which place. 

I would think it is better to achieve general consensus in the discussion first, and then have a FIP draft for refining.

**Comment by kaitlin-beegle** [comment]
> I think a basic problem here is that one might be confused to put comments here or in the discussion, and the author is willing to respond in which place.
> 
> I would think it is better to achieve general consensus in the discussion first, and then have a FIP draft for refining.

I agree! That is the process.  I've asked the team to be more proactive about following this going forward! 

Also, authors are responsible for addressing comments on both discussions and on the draft itself. Although community conversations are best held in the discussion, we don't want to restrict community members from commenting directly on drafts.

**Comment by jennijuju** [comment]
given the comments above - id like to propose converting this PR into a draft PR - and reopen for reviewing & FIP number assignment after FIP authors ack & address the valid/common comments from the discussion.

**Comment by jennijuju** [comment]
@vkalghatgi as suggested above, I converted this PR into a draft for now. Please feel free to reopen the PR once more details are added to the FIP draft and tag one of the editors to review!

**Comment by kaitlin-beegle** [comment]
Closing this PR; a new PR will soon be opened with an updated draft.

**Pull request closed without merging**
