### PR TITLE
Commit with expired deals

### PR DESCRIPTION
**Pull request by ZenGround0**
Writing needs to be polished but the main ideas are here.  Discussion issue: https://github.com/filecoin-project/FIPs/issues/152

@whyrusleeping any fundamental reason cbor-gen [can't do integer keyed maps](https://github.com/whyrusleeping/cbor-gen/blob/master/gen.go#L382)?  I want this datatype for this proposal and I'm hoping to be able to add cbor-gen support in 1-2 engineer days but let me know if there's a reason that's unrealistic.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@ZenGround0 that is a can of worms.

IPLD cannot do integer keyed maps, so as a result, cbor-gen does not support them.

**Comment by ZenGround0** [comment]
@zixuanzh I have some cryptoecon TODOs in this FIP draft PR.  I think they are straightforwardly not problems but I don't want to move forward without your sign off

**Comment by momack2** [comment]
@nicola - correct me if I'm wrong, but I believe if a miner never packs a deal into a sector, even after calling declare publish storage deals, they never lose a sector collateral (because all sectors they pack, not including that deal, are valid). Therefore I think we are already in the first case and should apply this change because it will have the beneficial impact of causing FEWER deals to need retries / fail to complete without actually changing the mental model. @arajasek @ZenGround0 - is that right?

**Comment by arajasek** [comment]
@momack2 Yes, that's right.

More generally, I think the current state is that a clear SLA doesn't necessarily exist today -- the strongest statement that can be made is that a Storage Provider _will_ lose their deal collateral if they publish a deal and then something* goes wrong (and this FIP doesn't change that). I don't think this FIP worsens the situation. Going awry between Pre and Prove Commit is something of an edge-case regardless. 

What is uncontroversial, IMO, is that nothing is gained by "trapping" a PreCommitted sector in an unCommittable state, forcing all the other deals in the sector to also necessarily fail to be activated. Seems like a pretty clear net bad to me, so I'd strongly advocate for this FIP.


```
*something can be:
- never precommitting a sector with the deal
- precommitting but not provecommitting the deal
- provecommitting (activating) the deal, but it then goes faulty
- (probably more)
```

**Comment by arajasek** [comment]
Thanks for the review, @nicola! 

> Questions:
> 
> * What happens today if the miner does not ever publish a sector for a published deal?
>   
>   * If the miner is does not lose sector collateral - then the system is already complex, so we may as well apply the change

Yeah, no sector collateral is lost, since none was ever locked up.

**Comment by arajasek** [comment]
@ZenGround0 Can we please slightly rename / reword this FIP, though? `Expired` has a certain definition w.r.t. deals that isn't quite what we're talking about here. 

Idk what the right term is, though..."Past-activation-deadline" deals? :P

**Comment by nicola** [comment]
> if a miner never packs a deal into a sector, even after calling declare publish storage deals, they never lose a sector collateral (because all sectors they pack, not including that deal, are valid).

I think that is true, which means that we already have strange edge cases (so maybe it's fine to add one more).

This is why I am trying to say that instead of adding edge cases we should try to simplify the protocol (or having a clearer Filecoin SLA)

**Comment by ZenGround0** [comment]
> This is why I am trying to say that instead of adding edge cases we should try to simplify the protocol (or having a clearer Filecoin SLA)

While I wrote this FIP I think this is exactly right.  With a couple weeks of reflection I am not enthusiastic about the complexity and technical debt this approach adds to the system.  While we can't handle this offchain with *absolute* certainty, we should be able to get very high guarantees against deals activating before commitment and avoid adding on chain complexity with scheduling in node software.  

To the extent that this is a problem storage providers are dealing with and want a fix for now I think the first step should be looking at what went wrong during node scheduling before we move to consider on chain solutions like this FIP.

I'm in support of including this as a *Deferred* FIP since the design will be useful in informing more significant refactors of the market / miner interface and filecoin SLA.  I'm also fine with moving this to *Rejected* and shutting down the PR since the closed PR documents the design well enough.

**Comment by jennijuju** [comment]
> This is why I am trying to say that instead of adding edge cases we should try to simplify the protocol (or having a clearer Filecoin SLA)

@nicola Why do you consider this an edge case? Also, a question, should the deals in the same sector, that may come from different clients, have an impact on other deals from a protocol perspective?

**Comment by jennijuju** [comment]
I disagree this FIP should be `Deferred` based on the conversation happening here, id suggests us to merge the draft and have a discussion in the issue.

**Comment by kaitlin-beegle** [comment]
Agreed; merging and moving to deferred.  Will merge and update to include FIP number and status.

**Comment by anorth** [comment]
@ZenGround0 @kaitlin-beegle let's close this PR somehow. Kaitlin and I have chatted and I believe she's now on board with merging FIP PRs sooner than when the FIP is completed/accepted. I would support merging this as-is, as `Deferred`. Kaitlin, if you concur, would you lift your requested change?

I think this underlying issue will be resolved by a more significant refactor of the miner<->market interactions that I am planning as part of enhancing programability for the implementation of alternative deal markets on FVM. This is helpful as a motivating problem, and we can reject if after it's actually fixed by another means.

**Review by anorth — APPROVED** [review]

**Pull request merged**
